### PR TITLE
Fix DB2 installation on test VM

### LINKED ISSUE #399: Test VM: DB2 installer failing to unpack DB2 gz archive
I noticed this happening during the previous issues but left this bit until now.

Perhaps this is Windows specific (shared folders). I have no Linux host to test this with at the moment.

The DB2 archives fails to be unpacked (file system/symlink errors): -

==> default: ---- Begin output of /var/dbfit/dbfit-java/db2/src/integration-test/resources/install_db2.sh -dl ----
==> default: STDOUT: install_db2.sh: INFO: found gzipped installation tarball. Unpacking...
==> default: STDERR: tar: expc/db2/linuxamd64/install/libdb2ure.so: Cannot create symlink to `libdb2ure.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/install/libdb2install_install.so: Cannot create symlink to `libdb2install_install.so.1': Proto
col error
==> default: tar: expc/db2/linuxamd64/install/libdb2osse_install.so: Cannot create symlink to `libdb2osse_install.so.1': Protocol er
ror
==> default: tar: expc/db2/linuxamd64/install/libdb2locale.so: Cannot create symlink to `libdb2locale.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/install/libdb2sec_install.so: Cannot create symlink to `libdb2sec_install.so.1': Protocol erro
r
==> default: tar: expc/db2/linuxamd64/install/libdb2genreg_install.so: Cannot create symlink to `libdb2genreg_install.so.1': Protoco
l error
==> default: tar: expc/db2/linuxamd64/install/libdb2isys.so: Cannot create symlink to `libdb2isys.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/install/libdb2locale_install.so: Cannot create symlink to `libdb2locale_install.so.1': Protoco
l error
==> default: tar: expc/db2/linuxamd64/install/libdb2dstf_install.so: Cannot create symlink to `libdb2dstf_install.so.1': Protocol er
ror
==> default: tar: expc/db2/linuxamd64/install/libdb2g11n_install.so: Cannot create symlink to `libdb2g11n_install.so.1': Protocol er
ror
==> default: tar: expc/db2/linuxamd64/install/libinpro_install.so: Cannot create symlink to `libinpro_install.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/install/libdb2jcc.so: Cannot create symlink to `libdb2jcc.so.1': Protocol error
==> default: tar: expc/db2/linuxamd64/bin/locale: Cannot create symlink to `../install/locale': Protocol error
==> default: tar: expc/db2/linuxamd64/utilities/db2ckupgrade/install/locale: Cannot create symlink to `../../../install/locale': Pro
tocol error
==> default: tar: expc/db2/linuxamd64/utilities/db2ckupgrade/bin/db2usrinf: Cannot create symlink to `../../../bin/db2usrinf': Proto
col error
==> default: tar: expc/db2/linuxamd64/utilities/db2ckupgrade/bin/db2langdir: Cannot create symlink to `../../../bin/db2langdir': Pro
tocol error
==> default: tar: expc/db2/linuxamd64/utilities/db2ckupgrade/bin/disp_msg: Cannot create symlink to `../../../bin/disp_msg': Protoco
l error
==> default: tar: Exiting with failure status due to previous errors
==> default: install_db2.sh: ERROR: unpacking gzipped installation tarball
==> default: ---- End output of /var/dbfit/dbfit-java/db2/src/integration-test/resources/install_db2.sh -dl ----
==> default: Ran /var/dbfit/dbfit-java/db2/src/integration-test/resources/install_db2.sh -dl returned 1
==> default: [2015-07-14T19:51:19+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit c
ode 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

### PR DESCRIPTION
**Pull request by MMatten**
Unpack DB2 installation archive to /tmp to avoid Vagrant/Windows shared folder issues to resolve #399.

### CODE REVIEW

File: dbfit-java/db2/src/integration-test/resources/install_db2.sh [hunk 1]
```diff
@@ -10,7 +10,8 @@ IM="$MODNAME: INFO:"
 EM="$MODNAME: ERROR:"
 WM="$MODNAME: WARNING:"
 
-DB2_INST_ROOT=/var/dbfit
+DBFIT_ROOT=/var/dbfit
+DB2_INST_ROOT=$DBFIT_ROOT
```
Comment (javornikolov) [inline dbfit-java/db2/src/integration-test/resources/install_db2.sh]: We're anyway resetting this to `/tmp` later - why not initialize it here directly to `/tmp`?

File: dbfit-java/db2/src/integration-test/resources/install_db2.sh [hunk 2]
```diff
@@ -107,6 +108,17 @@ elif [ -f db2_linuxx64_expc.tar.gz ]
 then
 	DOSETUP=true
 	echo "$IM found gzipped installation tarball. Unpacking..."
+
+	# Copy the installation package to /tmp before unpacking to avoid Vagrant shared folders issues.
+	cp db2_linuxx64_expc.tar.gz /tmp
```
Comment (javornikolov) [inline dbfit-java/db2/src/integration-test/resources/install_db2.sh]: I think we can skip the copy step (would save some disk space):
``` bash
DB2_INST_ROOT=/tmp
cd ${DB2_INST_ROOT} || { echo "Cannot change to ${DB2_INST_ROOT}; exit 1; }
tar --no-same-owner -zxf db2_linuxx64_expc.tar.gz ${DBFIT_ROOT}/db2_linuxx64_expc.tar.gz
...
```

File: dbfit-java/db2/src/integration-test/resources/install_db2.sh (hunk 1 above)
Comment (MMatten) [inline dbfit-java/db2/src/integration-test/resources/install_db2.sh]: This was to look in the DbFit root directory first as that's where my `expc` directory got left from the initial installation. It's not necessary. I'll update.

File: dbfit-java/db2/src/integration-test/resources/install_db2.sh (hunk 2 above)
Comment (MMatten) [inline dbfit-java/db2/src/integration-test/resources/install_db2.sh]: Good point. I'll just untar to `/tmp`.
