### PR TITLE
Fix MySQL vagrant test vm build

### LINKED ISSUE #568: Error building vagrant dev VM
Fails with: -
```
==> default: Installing Cookbook Gems:
==> default: Compiling Cookbooks...
==> default: 
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/git/libraries/z_provider_mapping.rb
==> default: ================================================================================
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: undefined method `set' for Chef::Platform:Class
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/git/libraries/z_provider_mapping.rb:6:in `<top (required)>'
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/git/libraries/z_provider_mapping.rb:
==> default: 
==> default:   1:  # provider mappings for Chef 11
==> default:   2:  
==> default:   3:  #########
==> default:   4:  # client
==> default:   5:  #########
==> default:   6>> Chef::Platform.set platform: :amazon, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:   7:  Chef::Platform.set platform: :centos, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:   8:  Chef::Platform.set platform: :debian, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:   9:  Chef::Platform.set platform: :fedora, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  10:  Chef::Platform.set platform: :mac_os_x, resource: :git_client, provider: Chef::Provider::GitClient::Osx
==> default:  11:  Chef::Platform.set platform: :redhat, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  12:  Chef::Platform.set platform: :scientific, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  13:  Chef::Platform.set platform: :smartos, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  14:  Chef::Platform.set platform: :solaris2, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  15:  Chef::Platform.set platform: :suse, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default: 
==> default: System Info:
==> default: ------------
==> default: chef_version=13.0.118
==> default: platform=centos
==> default: platform_version=7.3.1611
==> default: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default: program_name=chef-solo worker: ppid=4862;start=07:38:57;
==> default: executable=/opt/chef/bin/chef-solo
==> default: 
==> default: 
==> default: Running handlers:
==> default: [2017-04-22T07:39:05+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-04-22T07:39:05+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 08 seconds
==> default: [2017-04-22T07:39:05+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-04-22T07:39:05+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-04-22T07:39:05+00:00] ERROR: undefined method `set' for Chef::Platform:Class
==> default: [2017-04-22T07:39:05+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

### PR DESCRIPTION
**Pull request by MMatten**
Allow MySQL service to run on vagrant CentOS box that comes with SELinux running in enforcing mode.

Resolves #568

### CODE REVIEW

File: test_vm/vendor/cookbooks/dbfit_test/metadata.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@
 version          '0.3.0'
 depends          'mysql2_chef_gem'
 depends          'yum-mysql-community'
-depends          'mysql', '~> 8.2'
+depends          'mysql'
```
Comment (javornikolov) [inline test_vm/vendor/cookbooks/dbfit_test/metadata.rb]: Do we really need that change already? With `~> 8.2` we should be getting the latest 8.x >= 8.2.

File: test_vm/vendor/cookbooks/dbfit_test/recipes/selinux.rb [hunk 2]
```diff
@@ -0,0 +1,9 @@
+selinux_state 'SELinux Permissive' do
+  temporary true
+  action :permissive
+end
+
+selinux_state 'SELinux Permissive' do
```
Comment (javornikolov) [inline test_vm/vendor/cookbooks/dbfit_test/recipes/selinux.rb]: Can we give that other name? There used it be some caveats for resources with same name (I think Chef treats is as a single entity and runs it only once).

**Comment by javornikolov** [comment]
> Loosen SELinux enforcement to allow MySQL to run

The commit message is not quite reflecting the change (we had it loosened before but after reboot only).

**Comment by javornikolov** [comment]
> Updates for latest mysql2_chef_gem version

It might be good to refine a bit that commit message too since we update some other cookbooks too.

File: test_vm/vendor/cookbooks/dbfit_test/metadata.rb (hunk 1 above)
Comment (MMatten) [inline test_vm/vendor/cookbooks/dbfit_test/metadata.rb]: Ah, after reading the docs I thought this meant any `8.2.x` but not `8.3.0` or later.

**Comment by javornikolov** [comment]
Besides the other remarks, the approach implemented in `selinux.rb` looks good to me.

File: test_vm/vendor/cookbooks/dbfit_test/metadata.rb (hunk 1 above)
Comment (MMatten) [inline test_vm/vendor/cookbooks/dbfit_test/metadata.rb]: I'm still not sure what's going on here. The docs

https://docs.chef.io/cookbook_versions.html

suggest that it wouldn't use `8.3.1` but it does end up in `Berksfile.lock` if I include the `'~> 8.2'` constraint.

Comment (MMatten) [inline test_vm/vendor/cookbooks/dbfit_test/metadata.rb]: So why would we now want to keep this constraint?

Comment (javornikolov) [inline test_vm/vendor/cookbooks/dbfit_test/metadata.rb]: `~> 8.2` is pessimistic locking and means >= 8.2 and < 9.0. So `8.3.1` meets the constraint.

> So why would we now want to keep this constraint?

Well, I don't know should we keep it or not. The old setting has the constraint, I guess we did it with idea that:
* It reminds us that versions < 8.2 are problematic and prevents us from using them.
* Also it would not automatically jump to 9.0 which might have breaking changes (mysql cookbook has proven to be a bit brittle).

Essentially the question is do we prefer `~> 8.2` or `>= 8.2`. The latter will give us signal that there is version >= 9.0. Maybe that's not a bad thing - we're anyway locking the versions with the `Berksfile.lock` and testing if things still work OK upon changing it.

Up to your judgement whether to remove the dependency constraint. It might be better to have it as separate PR since I believe it doesn't contribute to fixing the broken provisioning this time.

Comment (MMatten) [inline test_vm/vendor/cookbooks/dbfit_test/metadata.rb]: I'm leaning towards `>= 8.2` and falling back to `~> 8.2` if the mysql cookbook develops new issues in 9.x. 

Agreed; a separate PR would be better.

**Comment by MMatten** [comment]
Ooops. Accidentally closed. I'm not sure how I did that.

**Comment by javornikolov** [comment]
> Ooops. Accidentally closed. I'm not sure how I did that.

No problem, there is reopen button which I just used :-)

**Comment by MMatten** [comment]
>> Ooops. Accidentally closed. I'm not sure how I did that.

> No problem, there is reopen button which I just used :-)

Thanks! I've made a few tweaks. Let me know what you think.

File: test_vm/vendor/cookbooks/dbfit_test/recipes/selinux.rb [hunk 3]
```diff
@@ -0,0 +1,9 @@
+selinux_state 'SELinux Permissive Temp' do
+  temporary true
+  action :permissive
+end
+
+selinux_state 'SELinux Permissive Perm' do
```
Comment (javornikolov) [inline test_vm/vendor/cookbooks/dbfit_test/recipes/selinux.rb]: *Perm* could mean permissive, permanent, ...

Comment (MMatten) [inline test_vm/vendor/cookbooks/dbfit_test/recipes/selinux.rb]: Ah. True.

Comment (MMatten) [inline test_vm/vendor/cookbooks/dbfit_test/recipes/selinux.rb]: I was also thinking that I should leave out the `temporary false` for the permanent mode change as `false` is the default but leaving in makes it more obvious. What's your view?

Comment (javornikolov) [inline test_vm/vendor/cookbooks/dbfit_test/recipes/selinux.rb]: Explicit `temporary` flag looks OK.

**Comment by MMatten** [comment]
Pushed again.

File: test_vm/vendor/cookbooks/dbfit_test/recipes/selinux.rb (hunk 3 above)
Comment (javornikolov) [inline test_vm/vendor/cookbooks/dbfit_test/recipes/selinux.rb]: If we come up with a good idea - we may try to get s support into selinux cookbook itself (e.g. scope=temporary|configuration-file|both.

File: test_vm/vendor/cookbooks/dbfit_test/metadata.rb (hunk 1 above)
Comment (javornikolov) [inline test_vm/vendor/cookbooks/dbfit_test/metadata.rb]: > I'm leaning towards >= 8.2 and falling back to ~> 8.2 if the mysql cookbook develops new issues in 9.x.

ok

File: test_vm/Berksfile.lock [hunk 4]
```diff
@@ -19,53 +17,57 @@ GRAPH
     iptables (>= 0.0.0)
     java (>= 0.0.0)
     lvm (>= 0.0.0)
-    mysql (~> 8.2)
+    mysql (>= 0.0.0)
```
Comment (javornikolov) [inline test_vm/Berksfile.lock]: Let's rebuild Berksfile.lock again

Comment (MMatten) [inline test_vm/Berksfile.lock]: Done.

**Comment by MMatten** [comment]
The VM is building well again :+1:

**Comment by javornikolov** [comment]
Thank you @MMatten! Looks good to me now, I'm merging it...
